Routes test for spectrums/set_search added
publiclab/spectral-workbench pull request #873
Opened 2022-01-25 15:51 UTC by anantraghuvanshi

Issue #862, required changes are done

Fixes #(update with issue number)

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- `rake test`
* [ ] code is in a uniquely-named feature branch and has been rebased on top of the latest master (especially if you've been asked to make additional changes)
* [ ] pull requests are descriptively named
* [ ] if possible, multiple commits squashed if they're smaller changes
* [ ] reviewed/confirmed/tested by another contributor or maintainer

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

Thanks!

2022-01-28 08:00 UTC, anantraghuvanshi commented
Hey @Tlazypanda, I have updated the file after the last test failed, kindly review it!

2022-01-28 20:18 UTC, Tlazypanda reviewed
Hey @anantraghuvanshi this actually overwrites one of our already existing tests :sweat_smile: can you please add it as a separate test?

2022-01-28 20:22 UTC, anantraghuvanshi commented
> Hey @anantraghuvanshi this actually overwrites one of our already existing tests sweat_smile can you please add it as a separate test?

I get it but how can I do that, may you guide me to that, because i didn't understand what that meant, sorry!

2022-02-01 16:04 UTC, Tlazypanda reviewed
Hey @anantraghuvanshi can you check the files changed tab on github where it show the `plot_rss` code being overwritten here? 
So we need to make sure that we are only adding the ` set_search` test without overwriting other existing tests

Once we make this change the pull request can be merged :tada: Thanks :v:

2022-02-01 17:04 UTC, anantraghuvanshi commented
Hi @Tlazypanda, this part of the file shows conflict, so if I simply delete that part alone I think it would fix the issue, right?</br> or is it that we need to write only those tests which are not present in `plot_rss`?
![image](https://user-images.githubusercontent.com/43936308/152014977-66f31ca0-c337-4dd4-8c3b-d2660049bf94.png)

2022-02-07 20:01 UTC, Tlazypanda reviewed
Hey @anantraghuvanshi Have resolved the conflicts but those were other tests not mentioning those if you can just add the `plots_rss` test that is being overwritten here that would be great! :tada: 
![Screenshot from 2022-02-08 01-27-07](https://user-images.githubusercontent.com/33183263/152862643-49157c16-8d19-400e-89ee-5fcdc353385d.png)

2022-02-22 09:16 UTC, TildaDares requested changes

2022-02-22 09:16 UTC, TildaDares commented on test/integration/routes_test.rb
> +   assert_routing({ path: '/spectrums/set_search', method: 'get' }, {controller: 'spectrums', action: 'show', id: 'set_search'})
```suggestion
   assert_routing({ path: '/spectrums/set_search', method: 'get' }, {controller: 'spectrums', action: 'set_search', id: 'set_search'})
```
@anantraghuvanshi The action should be `set_search`

2022-02-22 09:21 UTC, TildaDares commented on test/integration/routes_test.rb
> +   assert_routing({ path: '/spectrums/set_search', method: 'get' }, {controller: 'spectrums', action: 'show', id: 'set_search'})
Nevermind, the test would fail if the action was changed back to 'set_search'.

2022-02-22 09:21 UTC, TildaDares commented
This is ready to be merged!

2022-02-22 09:22 UTC, TildaDares approved these changes
Great work @anantraghuvanshi! Thank you

2022-02-22 09:22 UTC, merged

2022-02-22 09:23 UTC, TildaDares commented
Congratulations and welcome to Public Lab @anantraghuvanshi 🎉

2022-02-23 13:27 UTC, anantraghuvanshi commented
> Great work @anantraghuvanshi! Thank you

Thanks a lot, @TildaDares and thanks for helping through all the way!